version: 1.2
workflows:
   - name: "CHIP-seq"
     subclass: WDL
     primaryDescriptorPath: /rna-seq-pipeline.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - master
         tags:
             - /.*/
